version: "3"

services:
  influxdb:
    image: influxdb:2.7
    network_mode: host
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=fishesp32
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken

  telegraf:
    image: telegraf:latest
    network_mode: host
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    # entrypoint : this ensure Mosquitto server is up and ready to accept a new connection
    entrypoint: >
      bash -c '
        until timeout 1 bash -c "</dev/tcp/192.168.1.14/1883" 2>/dev/null; do
          echo "En attente de Mosquitto...";
          sleep 2;
        done;
        exec telegraf'

  grafana:
    image: grafana/grafana-oss
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  influxdb_data:
  grafana_data:

